//! Complete example demonstrating magic handlers for both Model and Resources
//!
//! This example shows how to use Syzygy's magic handler system to automatically
//! extract fields from both the Model and Resources using derive macros.

use syzygy::prelude::*;

// ============================================================================
// Application Model - User-specific state
// ============================================================================

#[derive(Debug, Clone, ModelExtractors)]
struct AppModel {
    #[extract]
    users: Vec<String>,
    
    #[extract]
    counter: i32,
    
    #[extract(as = CurrentUser)]
    current_user: Option<String>,
    
    #[extract(as = ActiveUser)]
    active_user: Option<String>,
    
    // This field won't be extractable
    internal_state: String,
}

// CurrentUser and ActiveUser are generated by the ModelExtractors derive macro

impl Default for AppModel {
    fn default() -> Self {
        Self {
            users: vec![],
            counter: 0,
            current_user: None,
            active_user: None,
            internal_state: "initialized".to_string(),
        }
    }
}

// ============================================================================
// Application Resources - System-wide services
// ============================================================================

#[derive(Debug, Clone)]
pub struct Database {
    pub connection_string: String,
}

#[derive(Debug, Clone)]
pub struct ApiClient {
    pub base_url: String,
    pub timeout_ms: u64,
}

#[derive(Debug, Clone)]
pub struct Logger {
    pub level: String,
}

#[derive(Debug, ResourceExtractors)]
struct AppResources {
    #[extract]
    database: Database,
    
    #[extract(as = MainApi)]
    main_api: ApiClient,
    
    #[extract(as = BackupApi)]
    backup_api: ApiClient,
    
    #[extract]
    logger: Logger,
    
    // This field won't be extractable
    cache: String,
}

// MainApi and BackupApi are generated by the ResourceExtractors derive macro

impl Default for AppResources {
    fn default() -> Self {
        Self {
            database: Database {
                connection_string: "sqlite://app.db".to_string(),
            },
            main_api: ApiClient {
                base_url: "https://api.example.com".to_string(),
                timeout_ms: 5000,
            },
            backup_api: ApiClient {
                base_url: "https://backup.example.com".to_string(),
                timeout_ms: 10000,
            },
            logger: Logger {
                level: "info".to_string(),
            },
            cache: "redis://localhost".to_string(),
        }
    }
}

// ============================================================================
// Events and Commands
// ============================================================================

#[derive(Debug, Clone)]
enum AppEvent {
    AddUser { name: String },
    UserAdded { name: String },
    SetCurrentUser { name: String },
    SystemStarted,
}

#[derive(Debug, Clone)]
enum AppCommand {
    SaveUser { name: String },
    LogEvent { message: String },
    BackupData,
}

// ============================================================================
// Magic Handlers - Automatically extract what they need
// ============================================================================

// Handler that extracts specific fields from the Model
fn handle_add_user(
    mut users: Vec<String>,
    counter: i32,
    current_user: CurrentUser,
) -> Dispatch<AppEvent, AppCommand> {
    let new_user = format!("user_{}", counter + 1);
    users.push(new_user.clone());
    
    println!("Added user: {} (total: {})", new_user, users.len());
    if let Some(current) = current_user.as_ref() {
        println!("Current user is: {}", current);
    }
    
    Dispatch::new(
        vec![AppEvent::UserAdded { name: new_user.clone() }],
        vec![AppCommand::SaveUser { name: new_user }],
    )
}

// Handler that extracts from Resources only
fn handle_system_startup(
    database: Database,
    main_api: MainApi,
    logger: Logger,
) -> Dispatch<AppEvent, AppCommand> {
    println!(
        "System starting with DB: {}, API: {}, Log level: {}",
        database.connection_string,
        main_api.base_url,
        logger.level
    );
    
    Dispatch::command(AppCommand::LogEvent {
        message: "System started successfully".to_string(),
    })
}

// Handler that uses backup services from Resources
fn handle_backup_request(
    backup_api: BackupApi,
    database: Database,
) -> Dispatch<AppEvent, AppCommand> {
    println!(
        "Backing up data to {} using DB {}",
        backup_api.base_url,
        database.connection_string
    );
    
    Dispatch::command(AppCommand::BackupData)
}

// Simple handler that doesn't use magic extraction for this demo
fn handle_set_current_user_simple(
    name: String,
) -> Dispatch<AppEvent, AppCommand> {
    println!("Set current user to: {}", name);
    
    Dispatch::command(AppCommand::LogEvent {
        message: format!("User {} is now active", name),
    })
}

// ============================================================================
// Main Event Handler - Routes events to magic handlers
// ============================================================================

fn handle_event(event: AppEvent, model: &mut AppModel) -> Dispatch<AppEvent, AppCommand> {
    match event {
        AppEvent::AddUser { .. } => {
            // Magic handler automatically extracts users, counter, current_user
            MagicHandler::call(handle_add_user, model)
        }
        AppEvent::SystemStarted => {
            // This would work if we had access to resources in the model handler
            // For now, we'll demonstrate with a simple response
            Dispatch::command(AppCommand::LogEvent {
                message: "System event received".to_string(),
            })
        }
        AppEvent::SetCurrentUser { name } => {
            // Simple handler for this demo
            handle_set_current_user_simple(name)
        }
        _ => Dispatch::none(),
    }
}

// ============================================================================
// Resource Handler - Shows magic extraction from resources
// ============================================================================

fn handle_command_with_resources(
    command: AppCommand,
    resources: &mut AppResources,
) -> Dispatch<AppEvent, AppCommand> {
    match command {
        AppCommand::BackupData => {
            // Magic handler automatically extracts needed resources
            MagicHandler::call(handle_backup_request, resources)
        }
        AppCommand::LogEvent { message } => {
            println!("LOG: {}", message);
            Dispatch::none()
        }
        _ => Dispatch::none(),
    }
}

// ============================================================================
// Main Function - Demonstrates the complete system
// ============================================================================

fn main() {
    println!("🎯 Magic Handlers Complete Example");
    println!("=====================================");
    
    // Create a Syzygy system with custom resources
    let (mut syzygy, handle) = Syzygy::builder()
        .model(AppModel::default())
        .event_handler(handle_event)
        .build();
    
    // Override with custom resources (would be better with builder pattern)
    *syzygy.model_mut() = AppModel::default();
    
    println!("\n📨 Testing Model Magic Handlers:");
    
    // Test adding users
    handle.dispatch(AppEvent::AddUser { name: "Alice".to_string() })
        .expect("Failed to dispatch AddUser event");
    
    handle.dispatch(AppEvent::AddUser { name: "Bob".to_string() })
        .expect("Failed to dispatch AddUser event");
    
    // Process events
    syzygy.process_events();
    
    println!("\n👤 Testing User State Management:");
    
    // Test setting current user
    handle.dispatch(AppEvent::SetCurrentUser { name: "Alice".to_string() })
        .expect("Failed to dispatch SetCurrentUser event");
    
    syzygy.process_events();
    
    println!("\n🔧 Testing Resource Magic Handlers:");
    
    // Demonstrate resource extraction
    let mut resources = AppResources::default();
    
    // Test backup handler (requires resources)
    let backup_result = handle_command_with_resources(
        AppCommand::BackupData,
        &mut resources,
    );
    
    println!("Backup command result: {} events, {} commands", 
             backup_result.events.len(), 
             backup_result.commands.len());
    
    // Test system startup handler - need to mix model and resources
    // For this demo, we'll just test the resource extraction separately
    let mut test_model = AppModel::default();
    test_model.users = vec!["demo_user".to_string()];
    
    // Create a handler that only needs model fields
    fn test_model_handler(users: Vec<String>, counter: i32) -> Dispatch<AppEvent, AppCommand> {
        println!("Model test: {} users, counter: {}", users.len(), counter);
        Dispatch::none()
    }
    
    let model_result = MagicHandler::call(test_model_handler, &mut test_model);
    println!("Model test result: {} events, {} commands", 
             model_result.events.len(), 
             model_result.commands.len());
    
    // Test resource-only handler
    let startup_result = MagicHandler::call(handle_system_startup, &mut resources);
    println!("Startup result: {} events, {} commands", 
             startup_result.events.len(), 
             startup_result.commands.len());
    
    println!("\n✨ Magic handlers successfully demonstrated!");
    println!("   - Model field extraction: ✅");
    println!("   - Resource field extraction: ✅");
    println!("   - Type-safe parameter resolution: ✅");
    println!("   - Newtype wrapper support: ✅");
}

// ============================================================================
// Additional Examples and Tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_model_magic_extraction() {
        let mut model = AppModel::default();
        model.users = vec!["test_user".to_string()];
        model.counter = 42;
        model.current_user = Some("alice".to_string());
        
        // Test the magic handler
        let result = MagicHandler::call(handle_add_user, &mut model);
        
        assert_eq!(result.events.len(), 1);
        assert_eq!(result.commands.len(), 1);
        
        if let AppEvent::UserAdded { name } = &result.events[0] {
            assert_eq!(name, "user_43");
        } else {
            panic!("Expected UserAdded event");
        }
    }
    
    #[test]
    fn test_resource_magic_extraction() {
        let mut resources = AppResources::default();
        
        // Test the magic handler with resources
        let result = MagicHandler::call(handle_system_startup, &mut resources);
        
        assert_eq!(result.commands.len(), 1);
        
        if let AppCommand::LogEvent { message } = &result.commands[0] {
            assert_eq!(message, "System started successfully");
        } else {
            panic!("Expected LogEvent command");
        }
    }
    
    #[test]
    fn test_field_extraction_types() {
        let model = AppModel::default();
        
        // Test direct extraction
        let users: Vec<String> = FromContainer::from_container(&model);
        assert_eq!(users.len(), 0);
        
        let counter: i32 = FromContainer::from_container(&model);
        assert_eq!(counter, 0);
        
        // Test newtype extraction
        let current_user: CurrentUser = FromContainer::from_container(&model);
        assert_eq!(*current_user, None);
        
        let active_user: ActiveUser = FromContainer::from_container(&model);
        assert_eq!(*active_user, None);
    }
    
    #[test]
    fn test_resource_extraction_types() {
        let resources = AppResources::default();
        
        // Test direct extraction
        let database: Database = FromContainer::from_container(&resources);
        assert_eq!(database.connection_string, "sqlite://app.db");
        
        let logger: Logger = FromContainer::from_container(&resources);
        assert_eq!(logger.level, "info");
        
        // Test newtype extraction
        let main_api: MainApi = FromContainer::from_container(&resources);
        assert_eq!(main_api.base_url, "https://api.example.com");
        
        let backup_api: BackupApi = FromContainer::from_container(&resources);
        assert_eq!(backup_api.base_url, "https://backup.example.com");
    }
}